### ISSUE TITLE
FEATURE REQUEST: IMPORT SVG PATHS

### ISSUE THREAD

**Issue by charlesr1971** [metafizzy/zdog#43] opened 2019-06-03 21:37 UTC
IMPORT SVG PATHS:

Please could we have the ability to import SVG. I have tried to convert an SVG path into zDog bezier & paths, but the outcome is not good. So, it would be great if we could have either an SVG Path converter utility or just the ability to work directly with an SVG & its paths.

**Comment by eeropic** [comment] 2019-06-03 21:50
Duplicate of https://github.com/metafizzy/zdog/issues/16

This is a good idea, but please check the existing issues before posting a new one.

**Closed** 2019-06-04 00:22 UTC
Labels: duplicate
