### ISSUE TITLE
module "vendor/boilerplate" is not defined 

### ISSUE THREAD

**Issue by dcsan** [metafizzy/zdog#14] opened 2019-05-29 11:24 UTC
I'm trying to use illo with WeChat miniprograms, which do support a Canvas to draw into.
However the environment is a bit different.

But even before hitting API differences I'm having problems importing the library.
I'm just using the raw dist.min

`import Zdog from "../../vendor/zdog.dist.min.js";`

also tried
`const zdog = require('../../vendor/zdog.dist.min.js')`

and getting the error below.

![image](https://user-images.githubusercontent.com/514002/58553276-1a79f580-8247-11e9-88f9-888a79926b3e.png)

sorry I can't really create a test case as this is not for a normal browser env but a canvas that lives inside WeChat messaging app

here's info on wechat's canvas API
https://developers.weixin.qq.com/miniprogram/dev/component/canvas.html

**Comment by dcsan** [comment] 2019-05-29 11:26
referenced here but only in the case of this being 'commonJS' module
https://github.com/metafizzy/zdog/blob/master/dist/zdog.dist.js#L235

**Comment by dcsan** [comment] 2019-05-29 11:51
I got a bit further with the NPM version of the library, but now hitting this error.

```
    console.log('Zdog', Zdog)
    console.log('Zdog', Zdog.Illustration)
```

shows that something is created, but `Zdog.Illustration is not a constructor` still blocks progress

![image](https://user-images.githubusercontent.com/514002/58555024-0df79c00-824b-11e9-9bf5-c632892d9267.png)

**Comment by dcsan** [comment] 2019-05-29 11:55
if anyone else is interested in this, wechat in general doesn't expose the `window` so i wrapped that out.

```js
if (window) {
  if ( window.PointerEvent ) {
    // PointerEvent, Chrome
    downEvent = 'pointerdown';
    moveEvent = 'pointermove';
    upEvent = 'pointerup';
  } else if ( 'ontouchstart' in window ) {
    // Touch Events, iOS Safari
    downEvent = 'touchstart';
    moveEvent = 'touchmove';
    upEvent = 'touchend';
  }
} else {
  console.warn('no pointer events')
}
```

**Comment by desandro** [comment] 2019-05-29 13:31
Thanks for reporting this issue. This sounds like duplicate of #10. Closing here

**Closed by desandro** 2019-05-29 13:31 UTC

**Comment by dcsan** [comment] 2019-05-30 02:50
I noted in that thread someone did a fix by adding to the window variable, but in our environment there is no window exposed to attach to...

----
I was able to fix by forcing the window variable after import
```
import Zdog from "zdog";
window.Zdog = Zdog;
```
